apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-api
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: sample-api
  template:
    metadata:
      labels:
        app: sample-api
    spec:
      containers:
      - name: sample-api
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 80
        resources:
{{ toYaml .Values.resources | indent 10 }}
