apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
data:
  username: {{ .Values.postgresql.postgresqlUsername | b64enc }}
  password: {{ .Values.postgresql.postgresqlPassword | b64enc }}
  database: {{ .Values.postgresql.postgresqlDatabase | b64enc }}
