postgresql:
  enabled: false
  postgresqlUsername: adminuser
  postgresqlPassword: StrongPassword!123
  postgresqlDatabase: mydatabase-dev
  service:
    port: 5432
  persistence:
    enabled: true
    size: 8Gi
