replicaCount: 2

image:
  repository: myacr.azurecr.io/sample-api
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80

postgresql:
  enabled: true
  postgresqlUsername: adminuser                # Admin username from your Terraform configuration or Azure CLI
  postgresqlPassword: StrongPassword!123           # Admin password from your Terraform configuration
  postgresqlDatabase: mydatabase-dev           # Database name retrieved from Azure
  service:
    port: 5432
  persistence:
    enabled: true
    size: 8Gi
