name: Deploy to AKS using Helm

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set up Helm
        uses: azure/setup-helm@v1

      - name: Install Kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'latest'  # Or specify a version if needed
          

      - name: Get AKS credentials
        run: az aks get-credentials --resource-group ${{ secrets.AKS_RESOURCE_GROUP }} --name ${{ secrets.AKS_CLUSTER_NAME }}

      - name: Verify kubectl connection
        run: kubectl get nodes

      - name: List Helm releases
        run: helm list 

      - name: Install or Upgrade Helm Release
        working-directory: helm
        run: |
          helm upgrade --install sample-api ./sample-api 



